# Generated by Django 2.1.5 on 2019-01-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190123_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('audio_track', models.FileField(upload_to='songs/')),
                ('album', models.ForeignKey(on_delete=None, to='works.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='album_song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='single_song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album_Song',
        ),
        migrations.DeleteModel(
            name='Single_Song',
        ),
    ]
