# Generated by Django 2.1.5 on 2019-01-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20190124_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_track',
            field=models.FileField(upload_to='media/'),
        ),
    ]
