# Generated by Django 2.1.5 on 2019-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20190125_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=200)),
                ('pic', models.FileField(upload_to='')),
                ('about', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
