# Generated by Django 2.1.5 on 2019-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
